spring:
  datasource:
    password: test-task
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true